In [3]:
subjects=["Americans","Indians"]
verbs=[" play"," watch"]
objects=[" Baseball"," Cricket"]
cml=[]
for i in range(len(subjects)):
    for j in range(len(verbs)):
        for k in range(len(objects)):
            c=subjects[i]+verbs[j]+objects[k]
            print(c)
        

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [25]:
def chk_inf():
    
        try:
            a=int(input('enter divisor'))
            b=int(input('enter dividend'))
            val = a/b
            print(val)
            
        except :
            print("divide by zero error!")
        
        
        finally:
            print("Finally, I executed!")
           

In [26]:
chk_inf()

enter divisor5
enter dividend0
divide by zero error!
Finally, I executed!


In [19]:
def askint(d):
        try:
            val = int(d)
        except:
            print("Looks like you did not enter an integer!")
            
        finally:
            print("Finally, I executed!")
        print(val) 

In [14]:
n=8
askint(n)

Finally, I executed!
8


In [15]:
class SideInput:
    def __init__(self,a,b,c):
        self.a=a
        self.b=b
        self.c=c
    def inputs(self):
        return "%f %f %f" %(self.a,self.b,self.c)

In [16]:
d=SideInput(4,5,6)
print(d)

In [19]:
import math
class CalcArea(SideInput):

        def __init__(self, a,b,c):
              super().__init__(a,b,c)
        def calc(self):
            s=(self.a+self.b+self.c)/2
            area=math.sqrt(s*(s-self.a)*(s-self.b)*(s-self.c))
            return area


In [21]:
d=CalcArea(4,13,15)
print(d.calc())


24.0


In [38]:
import numpy as np
ls=[1,2,3,4]
a=[]
np.array(np.power(ls,2))
for i in range(len(ls)):
    a.append(np.array(np.power(ls,i)))
print(a)
a

[array([1, 1, 1, 1], dtype=int32), array([1, 2, 3, 4], dtype=int32), array([ 1,  4,  9, 16], dtype=int32), array([ 1,  8, 27, 64], dtype=int32)]


[array([1, 1, 1, 1], dtype=int32),
 array([1, 2, 3, 4], dtype=int32),
 array([ 1,  4,  9, 16], dtype=int32),
 array([ 1,  8, 27, 64], dtype=int32)]

In [72]:
import math
ls=[1,2,3,4]
d=[]
x=[]
for i in range(len(ls)):
   
    for j in range(len(ls)):
        v=(math.pow(ls[i],j))
        #break
        d.append(v)
    x.append(d)
    d=[]
x

[[1.0, 1.0, 1.0, 1.0],
 [1.0, 2.0, 4.0, 8.0],
 [1.0, 3.0, 9.0, 27.0],
 [1.0, 4.0, 16.0, 64.0]]

In [75]:
def askint():
    while True:
        try:
            val = int(input("Please enter an integer: "))
        except:
            print("Looks like you did not enter an integer!")
            continue
        else:
            print('Yep thats an integer!')
            print(val)
            break
        finally:
            print("Finally, I executed!")
    print(val)
          

In [77]:
askint()

Please enter an integer: njn
Looks like you did not enter an integer!
Finally, I executed!
Please enter an integer: nbn
Looks like you did not enter an integer!
Finally, I executed!
Please enter an integer: njj
Looks like you did not enter an integer!
Finally, I executed!
Please enter an integer: b
Looks like you did not enter an integer!
Finally, I executed!
Please enter an integer: 4
Yep thats an integer!
4
Finally, I executed!
4
