# Q1. Write a Python program to get the string from the given string where all the occurrence of its first char has been changed to '$,' except first char itself?

In [6]:
st=list('prospectppp')
print(st)
j=0
for i in range(len(st)):
    if(st[i]=='p'):
        j+=1
        if(j>1):
            st[i]='$'
st
q="".join(st)
q    

['p', 'r', 'o', 's', 'p', 'e', 'c', 't', 'p', 'p', 'p']


'pros$ect$$$'

# Q2. Write a Python program to get the single string from the two given strings, and separated by the space and swap the first two characters of each string?

In [15]:
st1='abc'
st2='xyz'
st3=st1[:2]
s1=st3+st2[2:3]
st4=st2[:2]
s2=st4+st1[2:3]
s2+" "+s1


'xyc abz'

# Q3. Write the Python program to add 'ing' at the end of the given string (length of the string should be at least 3). If given string already ends with 'ing,' then add 'ly' instead. If string length of the given string is less than 3, leave it unchanged?

In [32]:
s=input('enter a string')
we=s.count('ing')
print(we)
if(len(s)>3):
    if(we>=1):
        s=s+'ly'
    else:
        s=s+'ing'
print('the ouput sring is',s)

enter a stringvv
0
the ouput sring is vv


In [ ]:
'The lyrics are not that poor!' 'The lyrics are poor!'

Expected Result: 'The lyrics are good!' 'The lyrics are poor!'

# Q4. Write the Python program to find the first appearance of the substring 'not' and 'poor' from the given string, if 'not' follows the 'poor', replace the whole 'not'...' poor' substring with 'good'.Return the resulting string.

In [47]:
stq='The lyrics are not that poor!' 
#stq='The lyrics are poor!'
diff=stq.find('that')-stq.find('not')
lt=stq.split(' ')
if(diff==4):
    ins=lt.index('not')
    lt.insert(ins,'good!')
    lt.remove('not')
    lt.remove('that')
    lt.remove('poor!')
    
" ".join(lt)

'The lyrics are good!'

In [127]:
stq='The lyrics are not that are not that not but poor!  ' 
stq=stq+" "
lt=stq.split(' ')
d=len(lt)-2
print(lt)
x=lt.count('poor!')
for i in range(d):
    
    if(lt[i]=='not' and lt[i+1]=='that'):
        print('hi')
        ins=lt.index('not')
        lt.insert(ins,'good!')
        lt.remove('not')
        lt.remove('that')
        if(x!=0):
            x=x-1       
            lt.remove('poor!')
        print(lt)
        d=len(lt)-2
        print(lt, d)
        


['The', 'lyrics', 'are', 'not', 'that', 'are', 'not', 'that', 'not', 'but', 'poor!', '', '', '']
hi
['The', 'lyrics', 'are', 'good!', 'are', 'not', 'that', 'not', 'but', '', '', '']
['The', 'lyrics', 'are', 'good!', 'are', 'not', 'that', 'not', 'but', '', '', ''] 10
hi
['The', 'lyrics', 'are', 'good!', 'are', 'good!', 'not', 'but', '', '', '']
['The', 'lyrics', 'are', 'good!', 'are', 'good!', 'not', 'but', '', '', ''] 9


IndexError: list index out of range

# Q5. Write the Python program to remove the characters which have odd index values of a given string.

In [152]:
lst=['gga','gggb','ggggc','fffffd','hhhhe','jjjjf']
newl=[]
#q=list(filter(lambda t:t%2==0,lst)
for i in range(len(lst)):
   
    if(i%2==0):
        newl.append(lst[i])
       
    
print('old list {0},new list after filtering is{1}'.format(lst,newl))

old list ['gga', 'gggb', 'ggggc', 'fffffd', 'hhhhe', 'jjjjf'],new list after filtering is['gga', 'ggggc', 'hhhhe']


# Q6. Write the Python function to get a string made of 4 copies of the last two characters of the specified string (length must be at least 2).

In [8]:
j=input('enter a string')
if(len(j)>2):
    a=j[-2:]*4
else:
    a=j
    
a

enter a stringlion


'onononon'

# Q7.Write the python function to get a string made of its first three characters of a specified string. If the length of the string is less than 3 then return the original string.

In [11]:
j=input('enter a string')
if(len(j)>3):
    a=j[:3]
else:
    a=j
    
a

enter a stringpyth


'pyt'

# Q8. Write the python program to print the following floating numbers up to 2 decimal places?

In [16]:
f=float(input('enter a float number'))
print("{0:.2f}".format(f))

enter a float number7.5345
7.53


# Q9. Write the Python program to format a number with a percentage

In [26]:
f=float(input('enter a float number'))
print("{0:.2%}".format(f))
print ("{0:.2%}".format(f/100))

enter a float number89.445
8944.50%
89.44%


# Q10. Write the Python program to count occurrences of a substring in a String?

In [4]:
s1='I will win, I will do it, I will conquer, I will clich it'
s2='will'
ou=s1.count(s2)
ou

4

# Q11. Write the Python program to count repeated characters in a string.

In [39]:
#k=input('enter a string')
#print(k.count('a'))
test='thequickbrownjumpsoverthelazydog'
t=list(test)
l=[]
for i in range(97, 97 + 26):
    x=t.count(chr(i))
    if(x>1):
        l.append(chr(i))
        print(chr(i),x)
l

e 3
h 2
o 3
r 2
t 2
u 2


['e', 'h', 'o', 'r', 't', 'u']

# Q12. Write the Python program to print the square and cube symbol in the area of a rectangle and volume of a cylinder?

In [34]:
# f'\N{GREEK SMALL LETTER GAMMA}={1.5:.2f} t/m\N{SUPERSCRIPT THREE}'
area=float(input('enter length of rectangle'))*float(input('enter breadth of the rectangle'))
import math
vol=math.pi*float(input('enter the radius of the cylinder'))**2*float(input('enter the height of the cylinder'))

print(f'\N{GREEK SMALL LETTER ALPHA}={area:.3f} m\N{SUPERSCRIPT TWO}')
print(f'Volume={vol:.2f} cm\u00b3')


enter length of rectangle1
enter breadth of the rectangle2
enter the radius of the cylinder3
enter the height of the cylinder4
α=2.000 m²
Volume=113.10 cm³


# Q13. Write the Python program to check if a string contains all letters of the alphabet?

In [43]:
k=input('enter a string')
if(k.isalpha()==1):
    print('only alphabets')
else:
    print('mixed')


enter a stringytuxtf
only alphabets


# Q14. Write the Python program to find the second most repeated word in a given string?

In [55]:
test='the quick brown jumps over the lazy dog gg gg gg yy yy yy yy iiii i i i i i i '
t=list(test.split(' '))
l=[]
l1=[]
print(t)
for i in range(len(t)-1):
    if(t[i]!=' '):
        x=t.count(t[i])
    #print(x)
        if(x>1):
            l.append(t[i])
            l1.append(x)
            
d=dict(zip(l1, l))

       
NumList = l1
print(NumList)
first = second = NumList[0]
for j in range( len(NumList)):
    if(NumList[j] > first):
        second = first
        first = NumList[j]
    elif(NumList[j] > second and NumList[j] < first):
        second = NumList[j]
        

print("The Largest Element in this List is : ", first)
print("The Second Largest Element in this List is : ", second)
print(d)

data = d.get(second)
data

['the', 'quick', 'brown', 'jumps', 'over', 'the', 'lazy', 'dog', 'gg', 'gg', 'gg', 'yy', 'yy', 'yy', 'yy', 'iiii', 'i', 'i', 'i', 'i', 'i', 'i', '']
[2, 2, 3, 3, 3, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6]
The Largest Element in this List is :  6
The Second Largest Element in this List is :  4
{2: 'the', 3: 'gg', 4: 'yy', 6: 'i'}


'yy'

# Q17. Write the Python program to count number of substrings from a given string of lowercase alphabets with exactly k distinct (given) characters?

In [12]:
inp='wolf'
k=3
num=0
li=list(inp)
if(k==len(inp)):
    num+=1
else:
    for i in range(len(inp)):
        for j in range(i + 1, len(inp)):
            res = [inp[i:j+1]]
            print(res)
            num+=1
        
num

['wo']
['wol']
['wolf']
['ol']
['olf']
['lf']


6

# Q30. Write the Python class to get all possible unique subsets from a set of distinct integers?


In [24]:
l=[4,5,6,7]
k=len(l)
num=[]
h=num

for i in range(len(l)):
    for j in range(i , len(l)+1):
        res = [l[i:j]]
        if(res!=[[]]):
            num.append(res)
num
num.sort()
num

[[[4]],
 [[4, 5]],
 [[4, 5, 6]],
 [[4, 5, 6, 7]],
 [[5]],
 [[5, 6]],
 [[5, 6, 7]],
 [[6]],
 [[6, 7]],
 [[7]]]

In [4]:
 Output =[[], [6], [5], [5, 6], [4], [4, 6], [4, 5], [4, 5, 6]]

In [25]:
class py_solution:
    def sub_sets(self, sset):
        return self.subsetsRecur([], sorted(sset))
    
    def subsetsRecur(self, current, sset):
        if sset:
            return self.subsetsRecur(current, sset[1:]) + self.subsetsRecur(current + [sset[0]], sset[1:])
        return [current]

print(py_solution().sub_sets([4,5,6,7])) 
# courtesy w3resource, using recurrsion

[[], [7], [6], [6, 7], [5], [5, 7], [5, 6], [5, 6, 7], [4], [4, 7], [4, 6], [4, 6, 7], [4, 5], [4, 5, 7], [4, 5, 6], [4, 5, 6, 7]]


In [26]:
Q31. Write the Python class to find a pair of elements (indices of the two numbers) from a given array whose sum equals the specific target number?

Object `number` not found.


# Q31. Write the Python class to find a pair of elements (indices of the two numbers) from a given array whose sum equals the specific target number

In [42]:
num= [10,20,10,40,50,60,70]
target=50 
#Output- 3, 4
for i in range(len(num)):
    
    for j in range(i+1,len(num)):
        val=num[i]+num[j]
        #print(val)
        if(val==target):
            g=num.index(num[i])
            k=num.index(num[j])
            t=(g,k)
            break
t

(0, 3)

# Q39. Write the Python program to create an instance of an OrderedDict using the given dictionary and sort dictionary during the creation and print members of the dictionary in reverse order?

In [13]:
countries={"Angola": 244, "Andorra": 376, "Algeria" :213, "Afghanistan": 93, "Albania":355}
l=list(countries.keys())
l.reverse()
l
rev_dict={}
for i in range(len(l)):
    g=(countries[l[i]])
    rev_dict.update({l[i]:g})
rev_dict

{'Albania': 355,
 'Afghanistan': 93,
 'Algeria': 213,
 'Andorra': 376,
 'Angola': 244}

In [18]:
from collections import OrderedDict
dict = {'Afghanistan': 93, 'Albania': 355, 'Algeria': 213, 'Andorra': 376, 'Angola': 244}
new_dict = OrderedDict(dict.items())
for key in new_dict:
    print (key, new_dict[key])

print("\nIn reverse order:")
for key in reversed(new_dict):
    print (key, new_dict[key]) 
    
# source W3rresource 

Afghanistan 93
Albania 355
Algeria 213
Andorra 376
Angola 244

In reverse order:
Angola 244
Andorra 376
Algeria 213
Albania 355
Afghanistan 93


# Q40.Write the Python program to compare two unordered lists (not sets)?

In [32]:
 
n1 = [30, 20, 10, 30, 20, 50]
n2 = [30, 20, 10, 30, 20, 50]
#n2 = [40, 20, 10, 30, 20, 50]
li=list(map(lambda x,y: x == y,n1,n2))
li
if(li.count(1)==len(li)):
    print('True')
else:
    print('False')


True


In [37]:
from collections import Counter
def compare_lists(x, y):
    print(Counter(x),Counter(y))
    return Counter(x) == Counter(y) # counts simillar value in a list imported from collections
#n1 = [20, 10, 30, 10, 20, 30]
n2 = [30, 20, 10, 30, 20, 50]
n1 = [30, 20, 10, 30, 20, 50]
print(compare_lists(n1, n2))

# source W3rresource 

Counter({30: 2, 20: 2, 10: 1, 50: 1}) Counter({30: 2, 20: 2, 10: 1, 50: 1})
True


# Q42. Write the Python program to convert an array to an array of machine values and return the bytes representation?

# Q41. Write the Python program to get an array buffer information?

In [72]:
from array import *
a=array('h',[2,3,45,7,8,1])
for i in a:
    print(i)
a.buffer_info()
ar=array('b', [118, 105, 110, 111, 116, 104])
ar1=array('i', [1, 2, 3, 4, 5, 6])
s=ar.tobytes()
print(s)

2
3
45
7
8
1
b'vinoth'


In [73]:
import array
import binascii
a = array.array('i', [1,2,3,4,5,6])
print("Original array:")
print('A1:', a)
bytes_array = a.tobytes()
print('Array of bytes:', binascii.hexlify(bytes_array))#courtesy W3R

Original array:
A1: array('i', [1, 2, 3, 4, 5, 6])
Array of bytes: b'010000000200000003000000040000000500000006000000'


# Q44. Write the Python program to push three items into the heap and return the smallest item from the heap. Also, return and pop the smallest item from the heap?

In [61]:
dict1={'VI': 5, 'VII': 3,'VIII': 1,'IX':2}
j=len(dict1)
k=list(dict1.values())
m=list(dict1.keys())
l=min(k)
c=k.index(l)
k.remove(k[c])
m.remove(m[c])


d1={}
for i in range(len(m)):
    d1.update({m[i]:k[i]})
d1
# please let me know any other easy program tech

{'VI': 5, 'VII': 3, 'IX': 2}

# Q46. Write the Python program to create the FIFO queue?

In [62]:
import queue
q = queue.Queue()
#insert items at the end of the queue 
for x in range(4):
    q.put(str(x))
#remove items from the head of the queue 
while not q.empty():
    print(q.get(), end=" ")
print("\n")


0 1 2 3 



In [74]:
n=int(input('enter a number'))
sum=0
for i in range(1,n+1):
    sum+=(1/float(i))
sum

enter a number2


1.5

In [92]:
import numpy as np
x=np.ones((5,5))*6

x[1:-1,1:-1] = 0
print(x)

[[6. 6. 6. 6. 6.]
 [6. 0. 0. 0. 6.]
 [6. 0. 0. 0. 6.]
 [6. 0. 0. 0. 6.]
 [6. 6. 6. 6. 6.]]


Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [94]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)


Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Q69. Write the NumPy program to create a new array of 3*5, filled with 2?

In [97]:
n=np.ones((3,5))*2
n1=np.ones((3,5))*2
print(n,n1)
Q50. Write the NumPy program to create an empty and a full array.

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]] [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [118]:
f=np.array([0, 12, 45.21 ,34, 99.91])

d=np.zeros(len(f))

for i in range(len(f)):
    s=(5/9)*(32-f[i])
    c[i]=(np.add(0,s))
    
print(c)

[ 17.77777778  11.11111111  -7.33888889  -1.11111111 -37.72777778]


In [125]:
com=np.array([ 1.00000000+88.j, 0.7+0.70710678j])
com
re=np.real(com)
im=np.imag(com)
print('the real parts are {},and the complex parts are{}'.format(re,im))

the real parts are [1.  0.7],and the complex parts are[88.          0.70710678]


In [205]:
h=np.array([ 0, 10, 20, 40, 60])
l=np.array([10,40])
print(np.in1d(h, l)) # w3resource
ls=[]

k=0
e=0
for i in range(len(l)):
    
    for j in range(len(h)):
        k=k+1         
        if(l[i]==h[j]):
            if(i>0 and h[j]==1):
                continue
                            
            ls.append(1)
        else:
            ls.append(0)
    ls1[i]=ls[e:k+1]
    e=k
d=ls1[0]
f=ls1[1]
re=[]
for i in range(len(h)):
    re.append(bool(int(d[i])+int(f[i])))
    

re


[False  True False  True False]


[False, True, False, True, False]

In [27]:
import numpy as np
arra = np.array([[ 1,  1,  0],
                 [ 0,  0,  0],
                 [ 0,  2,  3],
                 [ 0,  0,  0],
                 [ 0, -1,  1],
                 [ 0,  0,  0]])

print("Original array:")
print(arra)
temp = {(0, 0, 0)}
print(type(temp))
result = []
for idx, row in enumerate(map(tuple, arra)):
    if row not in temp:
        result.append(idx)
print("\nNon-zero unique rows:")
print(arra[result])


Original array:
[[ 1  1  0]
 [ 0  0  0]
 [ 0  2  3]
 [ 0  0  0]
 [ 0 -1  1]
 [ 0  0  0]]
<class 'set'>

Non-zero unique rows:
[[ 1  1  0]
 [ 0  2  3]
 [ 0 -1  1]]


In [35]:
import numpy as np
arra = np.array([[ 1,  1,  0],
                 [ 0,  0,  0],
                 [ 0,  2,  3],
                 [ 0,  0,  0],
                 [ 0, -1,  1],
                 [ 0,  0,  0]])


len(arra)
j=c=0

for i in range(len(arra)):
    for j in range(3):
        if(arra[i,j]==0):
            c+=1
            
    
    if(c==3):
        h=np.delete(arra,[i,j-1],0)
        print('g')
        
    c=0
    
h


g
g
g


array([[ 1,  1,  0],
       [ 0,  2,  3],
       [ 0,  0,  0],
       [ 0, -1,  1]])

# Q87. Write the NumPy program to multiply the matrix by another matrix of complex numbers and create a new matrix of complex numbers?

In [38]:
a=np.array([3+5j,5+6j])
b = np.array([5+6j,7+8j])
print(a*b)
print(np.vdot(a,b))

[-15.+43.j -13.+82.j]
(128-9j)


# Q88. Write a NumPy program to generate the matrix product of two Arrays?

In [39]:
x=np.array([[1, 0], [1, 1]])
y=np.array( [[3, 1], [2, 2]])
np.matmul(x,y)

array([[3, 1],
       [5, 3]])

# Q89. Write the NumPy program to find roots of the following Polynomials?

In [47]:
x=np.array([1,6,-9])
np.roots(x)

array([-7.24264069,  1.24264069])

# Q90. Write the NumPy program to calculate inverse of sine, cosine, and inverse tangent for all elements in a given array?
Sample output- Inverse sine- [-1.57079633 0. 1.57079633] Inverse cosine- [3.14159265 1.57079633 0. ] Inverse tangent- [-0.78539816 0. 0.78539816]

In [55]:
print(np.sin(0))
print(np.arccos(0))
print(np.arcsin(0))
print(np.arctan(1))


0.0
1.5707963267948966
0.0
0.7853981633974483


# Q91. Write the NumPy program to calculate the difference between in neighbouring elements, element-wise of a given array?

In [68]:
d=np.array([1 ,3 ,5 ,7 ,0])
g=[]
for i in range(len(d)-1,0,-1):
    g.append(d[i]-d[i-1])
#g.reverse()
g

[-7, 2, 2, 2]

# Q92. Write the Python program to find the maximum and the minimum value of a given flattened array?

In [70]:
f=np.array([[0, 1], [2, 3]])
print(np.max(f))
print(np.min(f))


3
0


# Q93. Write the NumPy program to calculate the difference between in the maximum and the minimum values of a given array along the second axis ?

In [76]:
b=np.array([[ 0, 1 ,2 ,3 ,4, 5], [ 6, 7, 8, 9, 10, 12]])
print(np.max(b[0])-np.min(b[0]))
print(np.max(b[1])-np.min(b[1]))

5
6


# Q94. Write the NumPy program to compute the weighted of the given array ?

In [80]:
b=np.array([0, 1 ,2 ,3 ,4])
np.average(b)


2.0

In [81]:
9/4


2.25

In [82]:
import numpy as np
x = np.arange(5)
print("\nOriginal array:")
print(x)
weights = np.arange(1, 6)
r1 = np.average(x, weights=weights)
r2 = (x*(weights/weights.sum())).sum()
assert np.allclose(r1, r2)
print("\nWeighted average of the said array:")
print(r1)



Original array:
[0 1 2 3 4]

Weighted average of the said array:
2.6666666666666665
